//! This program should be invoked by `cargo-packager` during its before-packaging steps.
//!
//! This program uses the current working directory as the app root
//! (for ./resources and ./dist). The --path-to-binary argument is used
//! to locate the target directory (useful in workspaces).
//!
//! ## Modes and CLI Arguments
//! This program runs in two modes, one for each kind of before-packaging step in cargo-packager.
//! It requires passing in three arguments:
//! 1. An operating mode, either `before-packaging` or `before-each-packager`.
//!    * Passing in `before-packaging` specifies that the `before-packaging-command` is being run
//!      by cargo-packager, which gets executed only *once* before cargo-packager generates any package bundles.
//!    * Passing in `before-each-package` specifies that the `before-each-package-command` is being run
//!      by cargo-packager, which gets executed multiple times: once for *each* package that
//!      cargo-packager is going to generate.
//!       * The environment variable `CARGO_PACKAGER_FORMAT` is set by cargo-packager to
//!         the declare which package format is about to be generated, which include the values
//!         given here: <https://docs.rs/cargo-packager/latest/cargo_packager/enum.PackageFormat.html>.
//!         * `app`, `dmg`: for macOS.
//!         * `deb`, `appimage`, `pacman`: for Linux.
//!         * `nsis`: for Windows; `nsis` generates an installer `setup.exe`.
//!         * `wix`: (UNSUPPORTED) for Windows; generates an `.msi` installer package.
//!    * A third mode, `verify-deb`, checks a *built* `.deb`: it installs the package
//!      (in a minimal container, or against the build host with `--host`), boots the app
//!      under `strace`, and fails if the app uses anything the declared deps don't cover.
//!      See `verify_deb.rs`. Args: `--deb <path>` (required), `--image <container-image>`,
//!      `--run-secs <n>`, `--host`, `--binary-name <name>`.
//! 2. The `--binary-name` argument, which specifies the name of the main binary that cargo-packager
//!    is going to package. This is the name of the binary that is generated by your app's main crate.
//! 3. The `--path-to-binary` argument, which specifies the path to the main binary that cargo-packager
//!    is going to package. This is the path to the binary that is generated by cargo when compiling
//!    your app's main crate.
//!
//! The following optional arguments can be passed in:
//! * `--add-deb-dep <package>`: (repeatable) adds a runtime dep to the generated `.deb`'s
//!   `Depends`. Most deps are found automatically, so this is just an escape hatch.
//! * `--optional-deb-dep-prefix <stem>`: (repeatable) marks a dlopen'd lib as optional,
//!   so it isn't declared, e.g. one the app handles the absence of.
//! * `--force-makepad`/`--force-no-makepad`: Forces the program to treat the app as a Makepad app
//!   or not a Makepad app, respectively. This means that Makepad-specific resource files must be copied in
//!   (and must succeed), or will not be copied in, respectively, and that
//!   Makepad-specific build configs will be enabled or disabled, respectively.
//!   * If neither `--force-makepad` nor `--force-no-makepad` is set, then the program will
//!     automatically detect whether the app is a Makepad app by checking if the `makepad-widgets` crate
//!     is a dependency of the app's main crate.
//! * `--host_os=<os>`: Overrides the host OS that is detected by the program. This is useful for testing
//!   the program on a different OS than the one that cargo-packager is running on.
//!
//! Set `$OBJDUMP` if you're cross-building, since the host's `objdump` can't read the
//! target's binaries (e.g. `OBJDUMP=aarch64-linux-gnu-objdump`).
//!
//! This program uses the `CARGO_PACKAGER_FORMAT` environment variable to determine
//! which specific build commands and configuration options should be used.
//!

pub mod makepad;
mod verify_deb;
use makepad::*;

use core::panic;
use std::{collections::{BTreeMap, BTreeSet}, ffi::OsStr, fs, path::{Path, PathBuf}, process::Command};

const EMPTY_ARGS: std::iter::Empty<&str> = std::iter::empty::<&str>();
const EMPTY_ENVS: std::iter::Empty<(&str, &str)> = std::iter::empty::<(&str, &str)>();


fn resolve_target_dir(path_to_binary: &Path, cwd: &Path) -> PathBuf {
    let abs_path = if path_to_binary.is_absolute() {
        path_to_binary.to_path_buf()
    } else {
        cwd.join(path_to_binary)
    };
    abs_path
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| cwd.to_path_buf())
}


fn main() -> std::io::Result<()> {
    let mut is_before_packaging = false;
    let mut is_before_each_package = false;
    let mut is_verify_deb = false;
    let mut main_binary_name = None;
    let mut path_to_binary = None;
    let mut host_os_opt: Option<String> = None;
    let mut extra_deb_deps: Vec<String> = Vec::new();
    let mut extra_optional_prefixes: Vec<String> = Vec::new();
    let mut deb_path: Option<PathBuf> = None;
    let mut image: Option<String> = None;
    let mut run_secs: u32 = 10;
    let mut host_mode = false;

    let mut args = std::env::args();
    // Skip argv[0] so a program path can't be mistaken for a mode.
    args.next();
    while let Some(arg) = args.next() {
        if arg.ends_with("before-packaging") || arg.ends_with("before_packaging") {
            is_before_packaging = true;
        }
        else if arg.contains("before-each") || arg.contains("before_each") {
            is_before_each_package = true;
        }
        else if arg == "verify-deb" || arg == "--verify-deb" {
            is_verify_deb = true;
        }
        else if arg == "--binary-name" {
            main_binary_name = Some(args.next().expect("Expected a binary name after '--binary-name'."));
        }
        else if arg == "--path-to-binary" {
            let path = PathBuf::from(args.next().expect("Expected a path after '--path-to-binary'."));
            path_to_binary = Some(path);
        }
        else if arg == "--add-deb-dep" {
            extra_deb_deps.push(args.next().expect("Expected a package name after '--add-deb-dep'."));
        }
        else if arg == "--optional-deb-dep-prefix" {
            extra_optional_prefixes.push(args.next().expect("Expected a library-stem prefix after '--optional-deb-dep-prefix'."));
        }
        else if arg == "--deb" {
            deb_path = Some(PathBuf::from(args.next().expect("Expected a path to a .deb after '--deb'.")));
        }
        else if arg == "--image" {
            image = Some(args.next().expect("Expected a container image after '--image'."));
        }
        else if arg == "--run-secs" {
            run_secs = args.next().expect("Expected a number after '--run-secs'.")
                .parse().expect("'--run-secs' expects an integer number of seconds.");
        }
        else if arg == "--host" {
            host_mode = true;
        }
        else if arg == "--force-makepad" {
            FORCE_MAKEPAD.set(true)
                .and(IS_MAKEPAD_APP.set(true))
                .expect("only --force-makepad OR --force-no-makepad can be set.");
        }
        else if arg == "--force-no-makepad" {
            FORCE_MAKEPAD.set(false)
                .and(IS_MAKEPAD_APP.set(false))
                .expect("only --force-makepad OR --force-no-makepad can be set.");
        }
        else if host_os_opt.is_none() && (arg.starts_with("--host_os") || arg.starts_with("--host-os")) {
            // Accept both `--host_os=<os>` and `--host_os <os>`.
            host_os_opt = arg
                .split_once('=')
                .map(|(_, v)| v.to_string())
                .or_else(|| args.next());
        }
    }

    let host_os = host_os_opt.as_deref().unwrap_or(std::env::consts::OS);

    match (is_before_packaging, is_before_each_package, is_verify_deb) {
        (true, false, false) => before_packaging(
            host_os,
            &main_binary_name.expect("Missing required argument '--binary-name'"),
        ),
        (false, true, false) => before_each_package(
            host_os,
            &main_binary_name.expect("Missing required argument '--binary-name'"),
            &path_to_binary.expect("Missing required argument '--path-to-binary'"),
            &extra_deb_deps,
            &extra_optional_prefixes,
        ),
        (false, false, true) => verify_deb::verify_deb(&verify_deb::VerifyDebArgs {
            deb_path: deb_path.expect("Missing required argument '--deb <path-to-deb>'"),
            image,
            binary_name: main_binary_name,
            run_secs,
            host_mode,
        }),
        _ => panic!("Please specify exactly one mode: 'before-packaging', 'before-each-package', or 'verify-deb'."),
    }
}

/// This function is run only *once* before cargo-packager generates any package bundles.
///
/// In fact, the current Makepad project doesn't need to use this function,
/// and we've kept all the infrastructure for the before-packaging command (in case we ever need it in the future).
fn before_packaging(_host_os: &str, _main_binary_name: &str) -> std::io::Result<()> {
    Ok(())
}


/// Whether to treat this app as a Makepad app, respecting `--force-makepad`/`--force-no-makepad`.
fn treat_as_makepad_app() -> bool {
    match FORCE_MAKEPAD.get() {
        Some(forced) => *forced,
        None => is_makepad_app(),
    }
}


/// Copy files from source to destination recursively.
fn copy_recursively(source: impl AsRef<Path>, destination: impl AsRef<Path>) -> std::io::Result<()> {
    fs::create_dir_all(&destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let filetype = entry.file_type()?;
        if filetype.is_dir() {
            copy_recursively(entry.path(), destination.as_ref().join(entry.file_name()))?;
        } else {
            fs::copy(entry.path(), destination.as_ref().join(entry.file_name()))?;
        }
    }
    Ok(())
}


/// The function that is run by cargo-packager's `before-each-package-command`.
///
/// It's just a simple wrapper that invokes the function for each specific package format.
fn before_each_package<P: AsRef<Path>>(
    host_os: &str,
    main_binary_name: &str,
    path_to_binary: P,
    extra_deb_deps: &[String],
    extra_optional_prefixes: &[String],
) -> std::io::Result<()> {
    // The `CARGO_PACKAGER_FORMAT` environment variable is required.
    let format = std::env::var("CARGO_PACKAGER_FORMAT")
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;

    let package_format = format.as_str();
    println!("Running before-each-package-command for {package_format:?}");

    // First run compilation - only copy resources if compilation succeeds
    match package_format {
        "app" | "dmg" => before_each_package_macos(   package_format, host_os, &main_binary_name, &path_to_binary)?,
        "deb"         => before_each_package_deb(     package_format, host_os, &main_binary_name, &path_to_binary, extra_deb_deps, extra_optional_prefixes)?,
        "appimage"    => before_each_package_appimage(package_format, host_os, &main_binary_name, &path_to_binary)?,
        "pacman"      => before_each_package_pacman(  package_format, host_os, &main_binary_name, &path_to_binary)?,
        "nsis"        => before_each_package_windows( package_format, host_os, &main_binary_name, &path_to_binary)?,
        _other => return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("Unknown/unsupported package format {_other:?}"),
        )),
    };

    let cwd = std::env::current_dir()?;
    let target_dir = resolve_target_dir(path_to_binary.as_ref(), &cwd);
    let dist_resources_dir = cwd.join("dist").join("resources");

    // Clear/delete existing resources directory to ensure no stale files
    if dist_resources_dir.exists() {
        fs::remove_dir_all(&dist_resources_dir)?;
    }
    fs::create_dir_all(&dist_resources_dir)?;

    {
        let app_resources_dest = dist_resources_dir.join(main_binary_name).join("resources");
        let app_resources_src = cwd.join("resources");
        println!("Copying app-specific resources...\n  --> From: {}\n      to:   {}", app_resources_src.display(), app_resources_dest.display());
        copy_recursively(&app_resources_src, &app_resources_dest)?;
    }

    // If this is a Makepad app, copy Makepad-specific resources
    if treat_as_makepad_app() {
        copy_makepad_resources(&dist_resources_dir, &target_dir)?;
    }
    println!("All resources copied successfully to: {}", dist_resources_dir.display());
    println!("  --> Done!");
    Ok(())
}


/// Runs the macOS-specific build commands for "app" and "dmg" package formats.
///
/// This function effectively runs the following shell commands:
/// ```sh
///    MAKEPAD_PACKAGE_DIR=../Resources  cargo build --workspace --release \
///    && install_name_tool -add_rpath "@executable_path/../Frameworks" ./target/release/_moly_app;
/// ```
fn before_each_package_macos<P: AsRef<Path>>(
    package_format: &str,
    host_os: &str,
    main_binary_name: &str,
    path_to_binary: P,
) -> std::io::Result<()> {
    assert!(host_os == "macos", "'app' and 'dmg' packages can only be created on macOS.");

    let extra_envs = if is_makepad_app() {
        Some(("MAKEPAD", "apple_bundle")).into_iter()
    } else {
        None.into_iter()
    };

    cargo_build(
        package_format,
        host_os,
        main_binary_name,
        EMPTY_ARGS,
        extra_envs,
    )?;

    // Use `install_name_tool` to add the `@executable_path` rpath to the binary.
    let install_name_tool_cmd = Command::new("install_name_tool")
        .arg("-add_rpath")
        .arg("@executable_path/../Frameworks")
        .arg(path_to_binary.as_ref())
        .spawn()?;

    let output = install_name_tool_cmd.wait_with_output()?;
    if !output.status.success() {
        eprintln!("Failed to run install_name_tool command: {}
            ------------------------- stderr: -------------------------
            {:?}",
            output.status,
            String::from_utf8_lossy(&output.stderr),
        );
        return Err(std::io::Error::new(std::io::ErrorKind::Other, "Failed to run install_name_tool command for macOS"));
    }

    Ok(())
}

/// Runs the Linux-specific build commands for AppImage packages.
fn before_each_package_appimage<P: AsRef<Path>>(
    package_format: &str,
    host_os: &str,
    main_binary_name: &str,
    path_to_binary: P,
) -> std::io::Result<()> {
    assert!(host_os == "linux", "AppImage packages can only be created on Linux.");

    cargo_build(
        package_format,
        host_os,
        main_binary_name,
        EMPTY_ARGS,
        EMPTY_ENVS,
    )?;

    strip_unneeded_linux_binaries(host_os, path_to_binary)?;
    Ok(())
}


/// Runs the Linux `.deb` build and writes the runtime deps to `./dist/depends_deb.txt`.
/// They come from three places:
/// 1. `dpkg-shlibdeps`, for every dynamically-linked lib (version-pinned, symbol-accurate).
/// 2. [`auto_runtime_deb_deps`], for what the linker can't see (dlopen'd libs, CA certs, etc.).
/// 3. `--add-deb-dep`, the manual escape hatch for anything still missed.
fn before_each_package_deb<P: AsRef<Path>>(
    package_format: &str,
    host_os: &str,
    main_binary_name: &str,
    path_to_binary: P,
    extra_deb_deps: &[String],
    extra_optional_prefixes: &[String],
) -> std::io::Result<()> {
    assert!(host_os == "linux", "'deb' packages can only be created on Linux.");

    cargo_build(
        package_format,
        host_os,
        main_binary_name,
        EMPTY_ARGS,
        EMPTY_ENVS,
    )?;

    let binary = fs::canonicalize(path_to_binary.as_ref())?;
    let dt_needed = dt_needed_sonames(&binary)?;

    let mut depends = compute_deb_depends_shlibdeps(main_binary_name, &binary)?;
    depends.extend(auto_runtime_deb_deps(&binary, &dt_needed, extra_optional_prefixes)?);
    // Safety net for `--ignore-missing-info`: make sure no linked lib was silently dropped.
    crosscheck_linked_deps(&dt_needed, &mut depends)?;
    let depends = merge_deb_depends(depends, extra_deb_deps);

    println!("Final .deb Depends: {}", depends.join(", "));
    std::fs::write("./dist/depends_deb.txt", depends.join("\n"))?;

    strip_unneeded_linux_binaries(host_os, path_to_binary)?;
    Ok(())
}


/// Folds the `--add-deb-dep` entries into the analyzed deps to get the final `Depends`.
///
/// Manual deps go in last and nothing drops them for being manual: the analysis can add
/// to what you asked for, never take it away.
///
/// Dedup is per package. Exact repeats collapse, and a bare `libfoo` is dropped when some
/// `libfoo (>= 1.0)` is also there, since the versioned one already implies it. But two
/// *different* constraints on the same package both stay -- dpkg ANDs them, and picking
/// one could silently weaken a version floor.
fn merge_deb_depends(analyzed: Vec<String>, extra: &[String]) -> Vec<String> {
    let mut depends = analyzed;
    depends.extend(extra.iter().cloned());
    depends.sort();
    depends.dedup();

    let constrained: BTreeSet<String> = depends.iter()
        .filter(|d| d.contains('('))
        .map(|d| deb_dep_package(d).to_string())
        .collect();
    // Leave alternatives (`a | b`) alone; their package name isn't the whole relation.
    depends.retain(|d| {
        d.contains('(') || d.contains('|') || !constrained.contains(deb_dep_package(d))
    });
    depends
}


/// The package name out of a Debian dependency relation, e.g. `libc6` from `libc6 (>= 2.39)`.
fn deb_dep_package(dep: &str) -> &str {
    dep.split([' ', '(']).next().unwrap_or(dep).trim()
}


/// Computes `.deb` runtime dependencies with `dpkg-shlibdeps`, the canonical
/// Debian tool: version-pinned (e.g. `libc6 (>= 2.34)`), direct, symbol-accurate.
fn compute_deb_depends_shlibdeps(package_name: &str, binary: &Path) -> std::io::Result<Vec<String>> {
    // dpkg-shlibdeps reads a `debian/` dir from its cwd; hand it a freshly-created
    // throwaway one (see `TempDir` -- a stale or pre-planted dir is never reused),
    // and `-O` so it prints `shlibs:Depends=...` to stdout instead of a substvars file.
    let workdir = TempDir::new("rpc-shlibdeps-")?;
    fs::create_dir(workdir.path().join("debian"))?;
    fs::write(
        workdir.path().join("debian").join("control"),
        format!("Source: {package_name}\n\nPackage: {package_name}\nArchitecture: any\n"),
    )?;

    let output = Command::new("dpkg-shlibdeps")
        .current_dir(workdir.path())
        .args(["-O", "--ignore-missing-info"])
        .arg(binary)
        .output()
        .map_err(|e| if e.kind() == std::io::ErrorKind::NotFound {
            std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "dpkg-shlibdeps not found; install it with 'sudo apt-get install dpkg-dev'",
            )
        } else {
            e
        })?;

    // Always surface dpkg-shlibdeps warnings (diversions, missing shlibs info, etc.),
    // which would otherwise be silently discarded on success.
    if !output.stderr.is_empty() {
        for line in String::from_utf8_lossy(&output.stderr).lines() {
            eprintln!("[dpkg-shlibdeps] {line}");
        }
    }

    if !output.status.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("dpkg-shlibdeps exited with {}", output.status),
        ));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let Some(list) = stdout.lines().find_map(|l| l.strip_prefix("shlibs:Depends=")) else {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            "dpkg-shlibdeps produced no 'shlibs:Depends=' line",
        ));
    };
    let depends: Vec<String> = list
        .split(',')
        .map(str::trim)
        .filter(|d| !d.is_empty())
        .map(str::to_string)
        .collect();
    Ok(depends)
}


/// A fresh directory under `$TMPDIR`, removed on drop (error paths included).
/// `create_dir` is atomic and fails if the path exists, so we only ever use one we just
/// made: a stale or pre-planted dir (say, one with a `debian/shlibs.local` that would
/// override dpkg-shlibdeps) gets skipped by bumping the suffix rather than reused.
struct TempDir(PathBuf);
impl TempDir {
    fn new(prefix: &str) -> std::io::Result<Self> {
        for n in 0..1000u32 {
            let path = std::env::temp_dir().join(format!("{prefix}{n}"));
            match fs::create_dir(&path) {
                Ok(()) => return Ok(Self(path)),
                Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => continue,
                Err(e) => return Err(e),
            }
        }
        Err(std::io::Error::new(
            std::io::ErrorKind::AlreadyExists,
            "failed to create a unique temporary directory",
        ))
    }
    fn path(&self) -> &Path {
        &self.0
    }
}
impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}


/// Libraries that Makepad dlopens but runs fine without (its GStreamer video stack),
/// so they shouldn't become hard `Depends`.
///
/// Only applied to Makepad apps: this is the one spot in the dep logic that can *drop*
/// a real dependency, so other apps shouldn't inherit Makepad's behavior. They can
/// declare their own with `--optional-deb-dep-prefix`.
const MAKEPAD_OPTIONAL_DLOPEN_STEM_PREFIXES: &[&str] = &[
    "libgst",
    "libglib-2.0",
    "libgobject-2.0",
    "libgio-2.0",
];

/// Programs the app spawns at runtime, found by name in the binary. Kept minimal on
/// purpose: a program name is a weak signal (ordinary words match by accident), so only
/// add entries confirmed in a real app.
const EXEC_TOOL_DEPS: &[(&str, &str)] = &[
    ("xdg-open", "xdg-utils"),
];

/// Finds runtime deps that `dpkg-shlibdeps` can't see because they aren't linked,
/// using only evidence in the binary itself:
/// * dlopen'd libs: dlopen takes the soname as a string, so it's in there somewhere
///   (e.g. Makepad's `libEGL.so.1`, rfd's `libdbus-1.so.3`).
/// * `ca-certificates`: if the app does TLS. libssl doesn't depend on it.
/// * `xdg-utils`: if the app spawns `xdg-open`.
/// * `desktop-file-utils` + `hicolor-icon-theme`: their dpkg triggers are what register
///   the `.desktop` file (deep links included) and icons that every cargo-packager `.deb` ships.
fn auto_runtime_deb_deps(
    binary: &Path,
    dt_needed: &[String],
    extra_optional_prefixes: &[String],
) -> std::io::Result<Vec<String>> {
    let bytes = fs::read(binary)?;
    let mut deps = Vec::new();

    // Every cargo-packager .deb ships a .desktop file and hicolor icons; these two
    // packages' dpkg triggers are what actually register them on the user's system.
    deps.push("desktop-file-utils".to_string());
    deps.push("hicolor-icon-theme".to_string());

    for (tool, pkg) in EXEC_TOOL_DEPS {
        if contains_bytes(&bytes, tool.as_bytes()) {
            println!("Auto-detected runtime dependency: {pkg} (binary spawns `{tool}`)");
            deps.push(pkg.to_string());
        }
    }

    let links_ssl = dt_needed.iter().any(|s| s.starts_with("libssl.so") || s.starts_with("libcrypto.so"));
    if links_ssl || contains_bytes(&bytes, b"/etc/ssl/certs") {
        println!("Auto-detected runtime dependency: ca-certificates (binary does TLS / reads the trust store)");
        deps.push("ca-certificates".to_string());
    }

    // No dlopen/dlmopen import means it can't dlopen anything, so any soname we found
    // would be a false positive.
    if !imports_dlopen(binary)? {
        println!("Binary does not import dlopen; skipping the dlopen'd-library scan.");
        return Ok(deps);
    }

    // Makepad's optional libs only apply to Makepad apps; see the const's docs.
    let makepad_optional: &[&str] = if treat_as_makepad_app() {
        MAKEPAD_OPTIONAL_DLOPEN_STEM_PREFIXES
    } else {
        &[]
    };
    let optional_prefixes: Vec<&str> = makepad_optional.iter().copied()
        .chain(extra_optional_prefixes.iter().map(String::as_str))
        .collect();

    // Find dlopen candidates: soname strings not covered by a linked library.
    let soname_offsets = find_soname_strings(&bytes);
    let dt_stems: BTreeSet<&str> = dt_needed.iter().map(|s| lib_stem(s)).collect();
    let mut by_stem: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for soname in soname_offsets.keys() {
        let stem = lib_stem(soname).to_string();
        if dt_stems.contains(stem.as_str()) {
            continue;
        }
        if optional_prefixes.iter().any(|p| stem.starts_with(p)) {
            println!("Skipping optional dlopen'd library: {soname} (app handles its absence)");
            continue;
        }
        by_stem.entry(stem).or_default().push(soname.clone());
    }
    if by_stem.is_empty() {
        return Ok(deps);
    }

    // Keep only sonames that code actually points at: a string can sit in the binary
    // without ever being loaded (an error message, say). Disassembly isn't cheap, so
    // this only runs once we have candidates.
    let referenced = code_referenced_addrs(binary)?;
    let sections = loadable_sections(binary)?;

    // If we couldn't read this arch's address forms, an empty set would reject every
    // candidate and silently drop real deps. Skip the filter instead: over-declaring
    // is the harmless direction.
    if referenced.is_empty() {
        eprintln!(
            "Warning: no code-referenced addresses found, so this binary's architecture \
            isn't understood here. Skipping the code-reference check and keeping all \
            dlopen candidates, which may over-declare dependencies."
        );
    }
    let apply_xref_filter = !referenced.is_empty();

    by_stem.retain(|_stem, sonames| {
        sonames.retain(|soname| {
            if !apply_xref_filter {
                return true;
            }
            let is_referenced = soname_offsets[soname].iter()
                .filter_map(|&off| file_off_to_vaddr(&sections, off as u64))
                .any(|vaddr| referenced.contains(&vaddr));
            if !is_referenced {
                println!("Skipping {soname}: no code references it (data only, not a dlopen argument).");
            }
            is_referenced
        });
        !sonames.is_empty()
    });

    let lib_paths = ldconfig_lib_paths()?;
    for (_stem, mut sonames) in by_stem {
        // Prefer the versioned soname (`libEGL.so.1`) over the bare dev symlink
        // (`libEGL.so`) that dlopen fallback chains also mention: the versioned one
        // is what's present on end-user systems, and the bare one is owned by -dev packages.
        sonames.sort();
        let soname = sonames.iter().rfind(|s| !s.ends_with(".so")).unwrap_or(&sonames[0]);
        let Some(path) = lib_paths.get(soname.as_str()) else {
            eprintln!(
                "Warning: dlopen candidate {soname} is not installed on this build host, \
                so its Debian package cannot be determined. \
                If the app requires it at runtime, add it manually via --add-deb-dep."
            );
            continue;
        };
        match dpkg_owning_package(path) {
            Some(pkg) => {
                println!("Auto-detected dlopen'd library dependency: {soname} -> {pkg}");
                deps.push(pkg);
            }
            None => eprintln!(
                "Warning: dlopen candidate {soname} ({}) is not owned by any dpkg package; \
                if the app requires it at runtime, add its package via --add-deb-dep.",
                path.display(),
            ),
        }
    }

    Ok(deps)
}


/// Safety net for `--ignore-missing-info`, which makes `dpkg-shlibdeps` silently omit
/// libs that lack shlibs info. Checks every linked lib's package made it into the list:
/// missing ones get added unversioned with a warning, and a linked lib owned by no
/// package at all is a hard error (we'd ship a `.deb` that can't be satisfied).
fn crosscheck_linked_deps(dt_needed: &[String], depends: &mut Vec<String>) -> std::io::Result<()> {
    let lib_paths = ldconfig_lib_paths()?;
    let covered = |depends: &[String], pkg: &str| depends.iter().any(|d| {
        d == pkg || d.starts_with(&format!("{pkg} ")) || d.starts_with(&format!("{pkg}:"))
    });
    for soname in dt_needed {
        // The dynamic linker itself is part of libc and often diverted; skip it.
        if soname.starts_with("ld-linux") || soname.starts_with("ld.so") {
            continue;
        }
        let Some(path) = lib_paths.get(soname.as_str()) else {
            eprintln!("Warning: linked library {soname} not found in the ldconfig cache; \
                cannot verify its .deb dependency.");
            continue;
        };
        match dpkg_owning_package(path) {
            Some(pkg) if covered(depends, &pkg) => {}
            Some(pkg) => {
                eprintln!("Warning: dpkg-shlibdeps omitted linked library {soname} \
                    (likely missing shlibs info); adding its package {pkg} unversioned.");
                depends.push(pkg);
            }
            None => return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "Linked library {soname} ({}) is not owned by any dpkg package, \
                    so the .deb's dependencies cannot be satisfied on end-user systems. \
                    (Bundling private libraries into a .deb is not supported.)",
                    path.display(),
                ),
            )),
        }
    }
    Ok(())
}


/// Whether the binary imports `dlopen`/`dlmopen` as undefined dynamic symbols,
/// i.e. whether it is capable of loading libraries at runtime at all.
fn imports_dlopen(binary: &Path) -> std::io::Result<bool> {
    let output = Command::new(objdump()).arg("-T").arg(binary).output()?;
    if !output.status.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("objdump -T exited with {}", output.status),
        ));
    }
    Ok(String::from_utf8_lossy(&output.stdout).lines().any(|l| {
        l.contains("*UND*") && matches!(l.split_whitespace().last(), Some("dlopen" | "dlmopen"))
    }))
}


/// Reads the binary's `DT_NEEDED` entries (directly-linked library sonames) via `objdump -p`.
fn dt_needed_sonames(binary: &Path) -> std::io::Result<Vec<String>> {
    let output = Command::new(objdump())
        .arg("-p")
        .arg(binary)
        .output()
        .map_err(|e| if e.kind() == std::io::ErrorKind::NotFound {
            std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "objdump not found; install it with 'sudo apt-get install binutils'",
            )
        } else {
            e
        })?;
    if !output.status.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("objdump -p exited with {}", output.status),
        ));
    }
    Ok(String::from_utf8_lossy(&output.stdout)
        .lines()
        .filter_map(|line| {
            let mut it = line.split_whitespace();
            (it.next() == Some("NEEDED")).then(|| it.next().map(str::to_string)).flatten()
        })
        .collect())
}


/// The part of a soname before `.so`, e.g. `libdbus-1` for `libdbus-1.so.3`.
/// Used to compare soname variants (`libEGL.so` vs `libEGL.so.1`) and to match
/// dlopen candidates against `DT_NEEDED` entries.
fn lib_stem(soname: &str) -> &str {
    &soname[..soname.find(".so").unwrap_or(soname.len())]
}


/// Scans the binary for embedded `lib<name>.so[.N]*` strings, the telltale sign of a
/// dlopen'd library. Returns each soname with every file offset it appears at, so callers
/// can check whether code actually references it (see [`code_referenced_addrs`]).
///
/// Has to match substrings at any offset, not whole printable strings: Rust literals
/// aren't NUL-terminated and get packed together in `.rodata`, so e.g. a Makepad binary
/// has `libEGL.so` and `libEGL.so.1` back-to-back as `libEGL.solibEGL.so.1`.
fn find_soname_strings(bytes: &[u8]) -> BTreeMap<String, Vec<usize>> {
    fn is_name_byte(b: u8) -> bool {
        b.is_ascii_alphanumeric() || matches!(b, b'_' | b'-' | b'+' | b'.')
    }
    const MAX_NAME_LEN: usize = 64;

    let mut found: BTreeMap<String, Vec<usize>> = BTreeMap::new();
    let mut i = 0;
    while i + 6 <= bytes.len() {
        if &bytes[i..i + 3] != b"lib" {
            i += 1;
            continue;
        }
        // Scan the name part until the first `.so` (names may contain dots, e.g.
        // `libgstreamer-1.0.so.0`, so we can't just split on the first dot).
        let mut j = i + 3;
        let mut end = None;
        while j < bytes.len() && j - i < MAX_NAME_LEN && is_name_byte(bytes[j]) {
            if bytes[j..].starts_with(b".so") {
                end = Some(j + 3);
                break;
            }
            j += 1;
        }
        let Some(mut end) = end else {
            i += 1;
            continue;
        };
        if end == i + 6 {
            // Empty name part ("lib.so"); not a real soname.
            i += 1;
            continue;
        }
        // Consume a trailing version suffix: (.digits)*
        while end + 1 < bytes.len() && bytes[end] == b'.' && bytes[end + 1].is_ascii_digit() {
            end += 1;
            while end < bytes.len() && bytes[end].is_ascii_digit() {
                end += 1;
            }
        }
        found.entry(String::from_utf8_lossy(&bytes[i..end]).into_owned()).or_default().push(i);
        i = end;
    }
    found
}


/// Virtual addresses that code points at, i.e. what tells a genuinely dlopen'd soname
/// apart from one that's just sitting in the file: a dlopen argument gets referenced by
/// an instruction, while a linked lib's soname lives in `.dynstr` and no instruction
/// mentions it.
///
/// Caveat: a soname reached only through a static pointer table looks unreferenced here.
/// We log candidates when we skip them, so that's at least visible in the build log.
fn code_referenced_addrs(binary: &Path) -> std::io::Result<BTreeSet<u64>> {
    use std::io::{BufRead, BufReader};
    let mut child = Command::new(objdump())
        .args(["-d", "--no-show-raw-insn"])
        .arg(binary)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()?;
    // Stream the disassembly: it can be millions of lines for a large binary.
    let stdout = child.stdout.take().expect("stdout was piped");
    let mut addrs = BTreeSet::new();
    // AArch64 forms an address across two instructions, so the page from the most
    // recent `adrp` per register has to be carried to the `add`/`ldr` that completes it.
    let mut adrp_pages: BTreeMap<String, u64> = BTreeMap::new();
    for line in BufReader::new(stdout).lines() {
        let line = line?;
        // x86-64: objdump resolves RIP-relative operands into a trailing
        // `# <addr>` comment, e.g. `lea -0x555083b(%rip),%rdi  # 7851b0 <...>`.
        if let Some(idx) = line.rfind("# ") {
            if let Some(tok) = line[idx + 2..].split_whitespace().next() {
                if let Ok(addr) = u64::from_str_radix(tok, 16) {
                    addrs.insert(addr);
                }
            }
        }
        collect_aarch64_addr(&line, &mut adrp_pages, &mut addrs);
    }
    if !child.wait()?.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            "objdump -d failed while collecting code references",
        ));
    }
    Ok(addrs)
}


/// Rebuilds AArch64 PC-relative addresses. Unlike x86-64's single RIP-relative operand,
/// these come from an instruction pair that objdump won't resolve into one comment:
/// ```text
///     adrp    x0, 785000        // page base
///     add     x0, x0, #0x376    // + offset  => 0x785376
/// ```
/// `adr` needs no pairing. We also record `ldr [reg, #off]` after an `adrp`, which
/// over-approximates (it might be a GOT slot), but that's the safe direction: an extra
/// address only keeps a candidate, it never drops a real one.
fn collect_aarch64_addr(
    line: &str,
    adrp_pages: &mut BTreeMap<String, u64>,
    addrs: &mut BTreeSet<u64>,
) {
    // With --no-show-raw-insn a line reads: "  4005c0:\tadrp\tx0, 785000 <sym>".
    let Some((_, code)) = line.split_once(':') else { return };
    let mut tokens = code.split_whitespace();
    let Some(mnemonic) = tokens.next() else { return };
    let operands: Vec<&str> = tokens.map(|t| t.trim_end_matches(',')).collect();

    let hex = |s: &str| u64::from_str_radix(s.trim_start_matches("0x"), 16).ok();
    let imm = |s: &str| {
        let s = s.trim_start_matches('#').trim_end_matches(']');
        if let Some(h) = s.strip_prefix("0x") { u64::from_str_radix(h, 16).ok() } else { s.parse().ok() }
    };

    match mnemonic {
        "adrp" if operands.len() >= 2 => {
            if let Some(page) = hex(operands[1]) {
                adrp_pages.insert(operands[0].to_string(), page);
            }
        }
        // `adr` encodes the full address, so objdump prints it directly.
        "adr" if operands.len() >= 2 => {
            if let Some(addr) = hex(operands[1]) {
                addrs.insert(addr);
            }
        }
        // `add xN, xM, #imm` completes the address begun by `adrp xM`.
        "add" if operands.len() >= 3 => {
            if let (Some(&page), Some(off)) = (adrp_pages.get(operands[1]), imm(operands[2])) {
                addrs.insert(page + off);
            }
        }
        // `ldr xN, [xM, #imm]` after `adrp xM` -- recorded conservatively.
        m if m.starts_with("ldr") && operands.len() >= 2 => {
            let base = operands[1].trim_start_matches('[');
            if let Some(&page) = adrp_pages.get(base) {
                let off = operands.get(2).and_then(|o| imm(o)).unwrap_or(0);
                addrs.insert(page + off);
            }
        }
        _ => {}
    }
}


/// The binary's loadable sections as `(file_offset, size, virtual_address)`,
/// read from `objdump -h`, for translating file offsets into virtual addresses.
fn loadable_sections(binary: &Path) -> std::io::Result<Vec<(u64, u64, u64)>> {
    let output = Command::new(objdump()).arg("-h").arg(binary).output()?;
    if !output.status.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("objdump -h exited with {}", output.status),
        ));
    }
    // Lines look like: " 11 .rodata  00466094  0000000000355000  0000000000355000  00355000  2**12"
    //                  idx name      size      vma               lma               file off  algn
    Ok(String::from_utf8_lossy(&output.stdout)
        .lines()
        .filter_map(|line| {
            let f: Vec<&str> = line.split_whitespace().collect();
            if f.len() < 7 || !f[1].starts_with('.') {
                return None;
            }
            let size = u64::from_str_radix(f[2], 16).ok()?;
            let vma = u64::from_str_radix(f[3], 16).ok()?;
            let file_off = u64::from_str_radix(f[5], 16).ok()?;
            // vma == 0 means the section isn't loaded into memory (debug info etc.).
            (vma != 0).then_some((file_off, size, vma))
        })
        .collect())
}


/// Translates a file offset into the virtual address it will be loaded at.
fn file_off_to_vaddr(sections: &[(u64, u64, u64)], off: u64) -> Option<u64> {
    sections.iter()
        .find(|(file_off, size, _)| off >= *file_off && off < file_off + size)
        .map(|(file_off, _, vma)| vma + (off - file_off))
}


/// Naive substring search over raw bytes.
fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
    haystack.windows(needle.len()).any(|w| w == needle)
}


/// The `objdump` to analyze the app binary with. Normally the host's, since a
/// `.deb` is built on the architecture it targets; `$OBJDUMP` overrides it for
/// cross-builds, where the host's objdump cannot read the target's binaries.
fn objdump() -> String {
    std::env::var("OBJDUMP").unwrap_or_else(|_| "objdump".to_string())
}


/// Maps sonames to library paths using the dynamic linker's cache (`ldconfig -p`).
fn ldconfig_lib_paths() -> std::io::Result<BTreeMap<String, PathBuf>> {
    let output = Command::new("ldconfig")
        .arg("-p")
        .output()
        .or_else(|e| if e.kind() == std::io::ErrorKind::NotFound {
            Command::new("/sbin/ldconfig").arg("-p").output()
        } else {
            Err(e)
        })?;
    if !output.status.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("ldconfig -p exited with {}", output.status),
        ));
    }
    // Lines look like: "\tlibEGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so.1".
    // First entry per soname wins (the primary arch is listed first on multiarch hosts).
    let mut map = BTreeMap::new();
    for line in String::from_utf8_lossy(&output.stdout).lines() {
        let Some((names, path)) = line.trim().split_once(" => ") else { continue };
        let Some(soname) = names.split_whitespace().next() else { continue };
        map.entry(soname.to_string()).or_insert_with(|| PathBuf::from(path.trim()));
    }
    Ok(map)
}


/// Finds which dpkg package owns the given library file (`dpkg -S`), trying the
/// path as-is first and its canonicalized target second (packages usually ship
/// the soname symlink, but some only register the real file).
fn dpkg_owning_package(path: &Path) -> Option<String> {
    fn query(path: &Path) -> Option<String> {
        let output = Command::new("dpkg").arg("-S").arg(path).output().ok()?;
        if !output.status.success() {
            return None;
        }
        String::from_utf8_lossy(&output.stdout)
            .lines()
            // Skip "diversion by ..." lines (e.g. NVIDIA's glx diversions).
            .find(|l| !l.starts_with("diversion") && l.contains(": "))
            // "libegl1:amd64: /usr/lib/..." -> "libegl1"
            .and_then(|l| l.split(':').next())
            .map(str::to_string)
    }
    query(path).or_else(|| query(&fs::canonicalize(path).ok()?))
}


/// Runs the Linux-specific build commands for PacMan packages.
///
/// This is untested and may be incomplete, e.g., dependencies are not determined.
fn before_each_package_pacman<P: AsRef<Path>>(
    package_format: &str,
    host_os: &str,
    main_binary_name: &str,
    path_to_binary: P,
) -> std::io::Result<()> {
    assert!(host_os == "linux", "Pacman packages can only be created on Linux.");

    cargo_build(
        package_format,
        host_os,
        main_binary_name,
        EMPTY_ARGS,
        EMPTY_ENVS,
    )?;

    strip_unneeded_linux_binaries(host_os, path_to_binary)?;
    Ok(())
}
    
/// Runs the Windows-specific build commands for WiX (`.msi`) and NSIS (`.exe`) packages.
fn before_each_package_windows<P: AsRef<Path>>(
    package_format: &str,
    host_os: &str,
    main_binary_name: &str,
    _path_to_binary: P,
) -> std::io::Result<()> {
    assert!(host_os == "windows", "'.exe' and '.msi' packages can only be created on Windows.");

    cargo_build(
        package_format,
        host_os,
        main_binary_name,
        EMPTY_ARGS,
        EMPTY_ENVS,
    )?;

    Ok(())
}

fn cargo_build<I, A, E, K, V>(
    package_format: &str,
    _host_os: &str,
    _main_binary_name: &str,
    extra_args: I,
    extra_envs: E,
) -> std::io::Result<()>
where
    I: IntoIterator<Item = A>,
    A: AsRef<OsStr>,
    E: IntoIterator<Item = (K, V)>,
    K: AsRef<OsStr>,
    V: AsRef<OsStr>,
{
    let mut cargo_build_cmd = Command::new("cargo");
    cargo_build_cmd
        .arg("build")
        .arg("--workspace")
        .arg("--release")
        .args(extra_args)
        .envs(extra_envs);

    if is_makepad_app() {
        cargo_build_cmd.env(
            "MAKEPAD_PACKAGE_DIR",
            &makepad_package_dir_value(package_format, _main_binary_name),
        );
    }

    let output = cargo_build_cmd
        .spawn()?
        .wait_with_output()?;
    if !output.status.success() {
        eprintln!("Failed to run cargo build command: {}
            ------------------------- stderr: -------------------------
            {:?}",
            output.status,
            String::from_utf8_lossy(&output.stderr),
        );
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("Failed to run cargo build command on {_host_os} for package format {package_format:?}")
        ));
    }

    Ok(())
}

/// Strips unneeded symbols from the Linux binary, which is required for Debian `.deb` packages
/// and recommended for all other Linux package formats.
fn strip_unneeded_linux_binaries<P: AsRef<Path>>(host_os: &str, path_to_binary: P) -> std::io::Result<()> {
    assert!(host_os == "linux", "'strip --strip-unneeded' can only be run on Linux.");
    let strip_cmd = Command::new("strip")
        .arg("--strip-unneeded")
        .arg("--remove-section=.comment")
        .arg("--remove-section=.note")
        .arg(path_to_binary.as_ref())
        .spawn()?;

    let output = strip_cmd.wait_with_output()?;
    if !output.status.success() {
        eprintln!("Failed to run strip command: {}
            ------------------------- stderr: -------------------------
            {:?}",
            output.status,
            String::from_utf8_lossy(&output.stderr),
        );
        return Err(std::io::Error::new(std::io::ErrorKind::Other, "Failed to run strip command for Linux"));
    }

    Ok(())
}
